# Generated by Django 5.1.1 on 2024-10-07 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_hotel_room_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="book_name",
        ),
    ]
