# Generated by Django 5.1.1 on 2024-10-11 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_user_book_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="bearth_day",
            new_name="birth_day",
        ),
    ]
